version: 2.1

tag-filter: &tag-filter
  tags:
    only: /^v.*/
  branches:
    ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run: echo "test"

workflows:
  test-workflow:
    jobs:
      - build:
         filters: *tag-filter
      - hold:
          type: approval
          requires:
            - build
          filters: *tag-filter
      - build:
          name: build-after-approval
          requires:
            - hold
          filters: *tag-filter
