version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8c:58:d9:f7:ca:8d:17:13:01:42:b5:c4:8e:5a:fe:82"
      - checkout 
      - run: echo "test"

workflows:
  test-workflow:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - build:
          name: build-after-approval
          requires:
            - hold
